// <auto-generated />
namespace ParseLogFile.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addnominationpageinfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnominationpageinfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201902181824542_add nomination page in file"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
